### ISSUE TITLE
Generator inputs and modeling changes

### ISSUE THREAD

**Issue by adfarth** [NREL/REopt.jl#109]
1. Add full- and half-load electric efficiency values for generator in addition to fuel (burn rate) slope and intercept inputs, to be used as the default method of input
a. Both are used in industry, but the REopt team has decided electric efficiency should be the primary input
b. `electric_efficiency_full_load`
c. `electric_efficiency_half_load`
c. Defaults for these values are 0
2. Update default installed cost, fixed O&M cost, and electric efficiency for `Generator` based on Jeff M.'s data

**Comment by Bill-Becker** [comment]
@hdunham I was thinking we could add all the proposed Generator changes from the SETO project to this task because we're going to be updating default cost and performance as well.

**Comment by Bill-Becker** [comment]
@hdunham Updated this issue per our discussion today, TBD a few details.

**Comment by Bill-Becker** [comment]
@hdunham Removed "add prime generator" from this issue list because that's a separate thing.

**Comment by hdunham** [comment]
> @hdunham Removed "add prime generator" from this issue list because that's a separate thing.

Ok, did you make a separate issue for that or does it exist already? @Bill-Becker

**Comment by Bill-Becker** [comment]
@hdunham I didn't make an issue because I didn't think it fell into the category of an "issue". We should use the "ERP Task List" spreadsheet for new features and capabilities that we want for that project. Another benefit of keeping it there is we need to coordinate that development with the UI developers as well, and they have overlapping tasks defined there too.

**Comment by hdunham** [comment]
@Bill-Becker @adfarth Looking back at this, I realized that I didn't quite follow the plan in the description above. I actually replaced the generator fuel burn slope and intercept inputs with the electric efficiency at full and half load inputs (instead of adding the latter and leaving the former as a secondary option). Do I need to add back in the option to use fuel burn inputs?

**Comment by Bill-Becker** [comment]
@hdunham I just forwarded you an old email with the consensus that we were going to replace the fuel burn inputs, so no need to add these back.

**Comment by Bill-Becker** [comment]
@hdunham Can you check what is needed to do here to finish this issue? I think we are not doing anything related to fuel storage cost, and in general I think we've done what we planned to do (revised plan, based on budget/time limits).

**Comment by Bill-Becker** [comment]
@hdunham This looks completed to me, so closing.
